site_name: 'five'
site_description: 'Main documentation for five'
repo_url: https://github.com/jaysuzi5/five
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'